version: '3.3'

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lmsstore
      - MYSQL_USER=lms
      - MYSQL_PASSWORD=12345678
    ports:
      - "3306:3306"
