server:
  port: 8080
  servlet:
    context-path: "/api/v1"

spring:
  data:
    rest:
      default-media-type: "application/json;charset=UTF-8"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lmsstore
    username: lms
    password: 12345678
    initializationMode: always
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
