package com.rls.lms.controllers;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.rls.lms.exceptions.JSONProcessingException;
import com.rls.lms.exceptions.MissingHeaderException;
import com.rls.lms.models.User;
import com.rls.lms.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/api/v1/users") // This means URL's start with /demo (after Application path)
public class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserRepository userRepository;

    @Autowired
    public UserController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @GetMapping(path="")
    public ResponseEntity<Iterable<User>> getAllUsers(@RequestHeader("RLS-Referrer") String domain) {
        if (domain == null || domain.isBlank())
            throw new MissingHeaderException("RLS-Referrer header is not present");
        // This returns a JSON or XML with the users
        return new ResponseEntity<>(userRepository.findAll(domain), HttpStatus.OK);
    }

    @PostMapping(path="/meta") // Map ONLY POST Requests
    public ResponseEntity<String> addNewUser (@RequestHeader("RLS-Referrer") String domain, @RequestBody User user) {
        if (domain == null || domain.isBlank())
            throw new MissingHeaderException("RLS-Referrer header is not present");
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        user.setId(domain+"_"+user.getUser_id());
        user.setDomain(domain);
        userRepository.save(user);
        return new ResponseEntity<>("User metadata saved successfully!", HttpStatus.OK);
    }

    @PatchMapping(path = "/meta")
    @SuppressWarnings("unchecked")
    public ResponseEntity<String> setMetadata(@RequestHeader("RLS-Referrer") String domain, @RequestBody Map<String, Object> payload) {
        if (domain == null || domain.isBlank())
            throw new MissingHeaderException("RLS-Referrer header is not present");

        Map<String, Object> payloadMetadata = (Map<String, Object>) payload.get("metadata");
        try {
            userRepository.patchMetadata((String) payload.get("user_id"), domain, payloadMetadata);
        } catch (JsonProcessingException e) {
            throw new JSONProcessingException(e.getMessage());
        }

        return new ResponseEntity<>("User metadata patched successfully!", HttpStatus.OK);
    }
}